#ifndef CAMSCREEN_LIST_WIDGET_GLOBAL_H
#define CAMSCREEN_LIST_WIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CAMSCREEN_LIST_WIDGET_LIB
# define CAMSCREEN_LIST_WIDGET_EXPORT Q_DECL_EXPORT
#else
# define CAMSCREEN_LIST_WIDGET_EXPORT Q_DECL_IMPORT
#endif

#endif // CAMSCREEN_LIST_WIDGET_GLOBAL_H
